menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'people', url: '/people'}
- {name: 'courses', url: '/courses'}
# - {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'C. Blake Wilson', 
  title: 'Assistant Professor', 
  department: 'Chemistry', 
  institution: 'University of Southern California', 
  institution_address: 'coming soon', 
  phone: 'coming soon', 
  email: 'coming soon', 
  office: 'coming soon', 
  lab: 'coming soon',
  image: 'assets/img/primary-investigator.jpg', 
  url: 'primary-investigator'
}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Coming Soon', url: 'Coming-soon'}

# <i class="fa-brands fa-bluesky"></i>
social:
- {icon: 'a-brands fa-bluesky', link: 'https://bsky.app/profile/blkwiln.bsky.social'}
- {icon: 'fa fa-twitter', link: 'https://x.com/blkwiln'}

contacts:
- {name: 'Dr. C. Blake Wilson', 
  title: 'Assistant Professor', 
  department: 'Chemistry', 
  institution: 'University of Southern California', 
  institution_address: 'coming soon', 
  phone: '(000) 000-0000', 
  email: 'coming soon', 
  office: 'coming soon', 
  image: 'assets/img/contact.jpg'
}
